import { createFileRoute } from "@tanstack/react-router";
import { BookOpen, HeartHandshake, Lightbulb, Sparkles } from "lucide-react";
import { CTASection, IconCard, PageHero, SectionHeading } from "@/components/site";
import studentsImage from "@/assets/grace-students.jpg";
import teachingImage from "@/assets/grace-teaching.jpg";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Grace Casa de profesores | Teacher Education in Areekode" }, { name: "description", content: "Learn about Grace Casa's mission to empower women through practical, career-focused teacher education." }, { property: "og:title", content: "About Grace Casa de profesores" }, { property: "og:description", content: "Empowering women through professional teacher education and practical learning." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });

const stages = [["01", "Learn", "Understand the concepts, methods, and principles of teaching."], ["02", "Practise", "Apply knowledge through practical activities and teaching exercises."], ["03", "Develop", "Improve communication, creativity, confidence, and professional skills."], ["04", "Prepare", "Get ready for interviews, teaching roles, and career opportunities."]];

function AboutPage() { return <>
  <PageHero eyebrow="About us" title="About Grace Casa de profesores" description="Empowering women through professional teacher education and practical learning." image={studentsImage} />
  <section className="section-space"><div className="site-container grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Who we are" title="Professional Training With a Human Focus" /><p className="mt-6 leading-8 text-muted-foreground">Grace Casa de profesores Montessori TTC, Areekode, is focused on professional teacher education and career-oriented training for women. We help students build the knowledge, practical exposure, communication skills, and confidence required to pursue careers in teaching.</p><p className="mt-5 leading-8 text-muted-foreground">Becoming a successful teacher requires more than academic qualifications. It calls for patience, creativity, classroom management, professional discipline, and real experience.</p></div><div className="grid gap-5 sm:grid-cols-2"><IconCard icon={<Lightbulb />} title="Our vision">Create confident, skilled, responsible women educators who contribute positively to children's development.</IconCard><IconCard icon={<HeartHandshake />} title="Our mission">Provide accessible teacher education through quality training, practical learning, and career guidance.</IconCard></div></div></section>
  <section className="section-space bg-secondary"><div className="site-container"><SectionHeading eyebrow="Our educational approach" title="From Learning to Professional Practice" align="center" /><div className="mt-12 grid gap-5 md:grid-cols-4">{stages.map(([n, title, copy]) => <article key={n} className="border-t-2 border-accent pt-6"><span className="font-display text-sm font-semibold text-accent">{n}</span><h3 className="mt-4 text-xl">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{copy}</p></article>)}</div></div></section>
  <section className="section-space"><div className="site-container grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><img src={teachingImage} alt="Teacher trainee leading a creative classroom activity" width={1408} height={1056} loading="lazy" className="aspect-[4/3] rounded-xl object-cover" /><div><SectionHeading eyebrow="Student-friendly environment" title="More Than Teacher Training" /><p className="mt-6 leading-8 text-muted-foreground">Students learn in a welcoming environment where they can interact with faculty, participate in activities, develop practical ability, and grow in confidence.</p><div className="mt-7 grid grid-cols-2 gap-3 text-sm">{["Arts and crafts", "Educational tours", "Study camps", "Field trips", "Exhibitions", "Site visits", "Seasonal celebrations", "Real teaching practice"].map((item) => <div key={item} className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-accent" />{item}</div>)}</div></div></div></section>
  <section className="bg-primary py-16 text-primary-foreground"><div className="site-container flex items-start gap-6"><BookOpen className="mt-1 h-9 w-9 flex-none text-accent" /><div><h2 className="text-3xl">Our Commitment</h2><p className="mt-4 max-w-3xl leading-8 text-primary-foreground/75">We are committed to practical, career-focused training that helps every student move forward with greater knowledge, ability, and professional confidence.</p></div></div></section>
  <CTASection />
</>; }
