import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BriefcaseBusiness, Check, Languages, Presentation, Shapes, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CTASection, IconCard, PageHero, SectionHeading } from "@/components/site";
import labImage from "@/assets/grace-practical-lab.jpg";

export const Route = createFileRoute("/courses")({ head: () => ({ meta: [
  { title: "Montessori & Pre-Primary TTC Courses | Grace Casa" }, { name: "description", content: "Explore Montessori TTC and Pre-Primary TTC programmes, eligibility, training focus, and career opportunities." }, { property: "og:title", content: "Professional Teacher Training Courses | Grace Casa" }, { property: "og:description", content: "Choose the right programme to begin your journey towards a career in education." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: CoursesPage });

function Checklist({ items }: { items: string[] }) { return <ul className="grid gap-3 sm:grid-cols-2">{items.map((item) => <li key={item} className="flex gap-2 text-sm leading-6"><Check className="mt-1 h-4 w-4 flex-none text-accent" />{item}</li>)}</ul>; }
function CoursesPage() { return <>
  <PageHero eyebrow="Our programmes" title="Professional Teacher Training Courses" description="Choose the right programme to begin your journey towards a career in education." image={labImage} />
  <section className="section-space"><div className="site-container"><div className="grid gap-10 lg:grid-cols-[0.36fr_0.64fr]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="eyebrow">Programme 01</p><h2 className="mt-4">Montessori TTC</h2><p className="mt-4 text-lg text-muted-foreground">Become a confident Montessori educator.</p><div className="mt-6 inline-block rounded-full bg-sand px-4 py-2 text-sm font-semibold text-primary">Eligibility: SSLC / Plus Two / Degree</div></div><div><p className="text-lg leading-8 text-muted-foreground">The Montessori TTC programme combines theoretical understanding with practical training in teaching methods, classroom activities, child-focused learning, and professional practice.</p><h3 className="mt-9 text-xl">What the course focuses on</h3><div className="mt-6 grid gap-5 sm:grid-cols-2">{[[<Shapes />, "Montessori education", "Understand Montessori principles and child-centred approaches."], [<Presentation />, "Practical teaching", "Develop skills through activities and teaching exercises."], [<Users />, "Child development", "Understand the needs and learning characteristics of children."], [<Languages />, "Communication", "Build professional classroom and workplace communication."]].map(([icon,title,copy]) => <IconCard key={title as string} icon={icon} title={title as string}>{copy}</IconCard>)}</div><div className="mt-8 rounded-xl bg-secondary p-7"><h3 className="text-xl">Montessori Practical Lab</h3><p className="mt-3 leading-7 text-muted-foreground">Our specialised lab gives students hands-on exposure, helping them apply teaching concepts and build confidence for real classroom situations.</p></div></div></div></div></section>
  <section className="section-space bg-primary text-primary-foreground"><div className="site-container grid gap-10 lg:grid-cols-[0.36fr_0.64fr]"><div><p className="eyebrow">Programme 02</p><h2 className="mt-4">Pre-Primary TTC</h2><p className="mt-4 text-lg text-primary-foreground/70">Prepare to teach young learners.</p><div className="mt-6 inline-block rounded-full bg-primary-foreground/10 px-4 py-2 text-sm font-semibold">Minimum qualification: SSLC</div></div><div><p className="text-lg leading-8 text-primary-foreground/75">Designed for women who want to develop essential early-childhood teaching, classroom, communication, creativity, and practical skills.</p><h3 className="mt-9 text-xl">Course objectives</h3><div className="mt-6"><Checklist items={["Handle and communicate with young learners", "Conduct creative classroom activities", "Organise age-appropriate learning", "Support children's early development", "Manage classroom situations", "Build confidence as an educator"]} /></div><h3 className="mt-9 text-xl">Where can you work?</h3><p className="mt-3 leading-7 text-primary-foreground/70">English medium schools, play schools, nurseries, kindergartens, and structured pre-primary learning environments.</p></div></div></section>
  <section className="section-space"><div className="site-container"><SectionHeading eyebrow="Professional development" title="Support Beyond Academic Learning" align="center" /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[<Languages />,"Spoken English","Improve communication and professional confidence."],[<Presentation />,"Interview training","Prepare for interviews and present yourself professionally."],[<BriefcaseBusiness />,"Career support","Receive placement assistance and career-oriented guidance."],[<Shapes />,"Creative learning","Develop arts, crafts, and classroom activity skills."]].map(([i,t,c]) => <IconCard key={t as string} icon={i} title={t as string}>{c}</IconCard>)}</div><div className="mt-12 flex flex-col items-start justify-between gap-6 border-y border-border py-8 md:flex-row md:items-center"><div><h3 className="text-2xl">Affordable, accessible training</h3><p className="mt-2 text-muted-foreground">Ask us about current course fees and admission details.</p></div><Button asChild size="lg"><Link to="/contact">Enquire about course & fees <ArrowRight /></Link></Button></div></div></section>
  <CTASection />
</>; }
